// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ffprobe} from '../models';

export function GetStartupFile():Promise<string>;

export function GetVideoMetadata(arg1:string):Promise<ffprobe.ProbeData>;

export function SelectFile():Promise<string>;
