// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartupFile() {
  return window['go']['main']['App']['GetStartupFile']();
}

export function GetVideoMetadata(arg1) {
  return window['go']['main']['App']['GetVideoMetadata'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
